
# Use containers.
sudo: false

dist: xenial

language: python

python:
  - 3.6
  
addons:
  apt:
    packages:
      - scons

# headless as some of the tests will show the GUI.
#
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
#
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - pwd
  - git --version
  - python3 --version
  - pip install --upgrade pip
  
  # Install dependencies.
  - pip3 install pyqt5
  - pip3 install numpy
  - pip3 install scipy
  - pip3 install pillow
  - pip3 install pyqtgraph
  - pip3 install matplotlib
  - pip3 install tifffile
  - pip3 install pyserial
  - pip3 install pytest
  - pip3 install pytest-forked
  - pip3 install pytest-mock
  - pip3 install pytest-qt
  - pip3 install pytest-xdist

  # Install storm-analysis (lite.. we only need the datareader.py file for the tests).
  - cd ..
  - git clone https://github.com/ZhuangLab/storm-analysis
  - ls

  # stackoverflow - https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath
  - export PYTHONPATH="${PYTHONPATH}:`pwd`/storm-analysis/"
  - export PYTHONPATH="${PYTHONPATH}:`pwd`/storm-control/"
  - python -c "import sys; print(sys.path)"
  
  # build C libraries.
  - ls
  - cd storm-control
  - scons

  # test
  - cd storm_control/test
  - py.test --forked
